languaje: node_js
cache:
  directories:
    - ~!@/.npm
node_js:
  - '10.16.3'
git:
  depth: 3
script:
  - yarm build
  - echo 'Aqui_tengo_que_poner_mi_domini_personalizado' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true 
  keep-history: true 
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop

